# S3Client initializes py_s3 only when connect is called

    Code
      print(client)
    Output
      S3Client:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        role: NULL 
        connected: FALSE 

---

    Code
      client$connect()
    Condition
      Error in `value[[3L]]()`:
      ! Error in connect()
      i Error in connect()

---

    Code
      print(client)
    Output
      S3Client:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        role: NULL 
        connected: FALSE 

---

    Code
      client$connect()

---

    Code
      print(client)
    Output
      S3Client:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        role: NULL 
        connected: TRUE 

# S3Client connect method works correctly

    Code
      client$connect()
      print(client)
    Output
      S3Client:
        tmproot: <temp_dir>
        bucket: my_bucket 
        prefix: data/ 
        s3root: NULL 
        role: NULL 
        connected: TRUE 

